### PR TITLE
Adds credo

### PR DESCRIPTION
**Pull request by Danwhy**
Adds credo and fixes most of the issues found by it
ref #147

### CODE REVIEW

**Comment by samhstn** [comment]
Nice, your the first to be using credo btw. It looked stricter (and maybe better) than dogma (recommended by @tonydaly). @Danwhy I'd be keen to hear your thoughts on it when I'm next in

**Comment by samhstn** [comment]
@Danwhy Not a big deal if your not keen to sort these out (their tedious I know), I've added some fixes for a couple of the warnings thrown up by `mix credo --strict` (was interested by how strict it was), what are your thoughts on fixing the rest of them? (I'm easy with whatever).

Most of the ones that are left are long line issues, from the few of these that I've fixed, I've found it made the code much easier to read.

Also what do you think about non 0 erring if the linter fails? Also running the linter on ci? Credo badge (or something like that)?

**Comment by samhstn** [comment]
Also, do you think you could fix lines like [this](https://github.com/research-resource/research_resource/pull/214/commits/ac54651ee648cba69a245f7e7bb5760a53f44721#diff-4b6da44bfd0bd2ccfe0c70cc188d7d2bL44) (I know it wasn't you btw), I find it a bit tricky to read

**Comment by tonydaly** [comment]
The main reason we chose credo on Healthlocker is that [HoundCI](https://houndci.com/configuration#elixir) uses it. But there's a decent write-up about the differences between credo and dogma here: http://trivelop.de/2015/11/26/comparison-dogma-credo/

**Comment by samhstn** [comment]
Thanks for the link @tonydaly nice read.

It looks like Credo is now more popular and better maintained (also has fair few more stars). Let's use Credo also for consistency among the projects. https://elixir.libhunt.com/project/dogma/vs/credo

**Comment by Danwhy** [comment]
Thanks @shouston3, this looks good. I'll have a look at fixing the minor issues credo raises when I get a chance. Might be best to leave this PR unmerged for today though as there's a client demo happening soon

**Pull request closed without merging**
